---
# tasks file for nginx
 - name: Import Nginx repository key
   apt_key:
      id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
      url: https://nginx.org/keys/nginx_signing.key
      state: present
 - name: Setup Nginx apt repository
   apt_repository:
      repo: deb http://nginx.org/packages/ubuntu focal nginx
      state: present
 - name: Install Nginx
   apt:
      name: nginx
      state: present
      update_cache: true
 - name: Adding nginx user to www-data group
   user:
     name: nginx
     append: true
     groups: www-data
 - name: Start Nginx, ensure it automatically starts on boot
   service:
      name: nginx
      enabled: true
      state: started


