---
# tasks file for mariadb
- name: Install MariaDB
  apt:
    pkg:
      - mariadb-server
      - python3-mysqldb
    state: latest
    update_cache: true
- name: Start MariaDB
  service:
    name: mariadb
    enabled: true
    state: started
- name: Update MariaDB root password
  mysql_user:
    name: root
    host: localhost
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    user: root
    password: "{{ mariadb_root_password }}"
    check_implicit_admin: true
    priv: "*.*:ALL,GRANT"
